import {bigint, boolean, date, index, integer, jsonb, pgTable, primaryKey, smallint, text, timestamp, unique, uuid} from 'drizzle-orm/pg-core';

const createdAt=timestamp('created_at',{withTimezone:true}).notNull().defaultNow();
export const categories=pgTable('categories',{id:uuid('id').defaultRandom().primaryKey(),slug:text('slug').notNull().unique(),name:text('name').notNull()});
export const articles=pgTable('articles',{id:uuid('id').defaultRandom().primaryKey(),canonicalSlug:text('canonical_slug').notNull().unique(),status:text('status').notNull().default('published'),categoryId:uuid('category_id').references(()=>categories.id),author:text('author').notNull().default('ELEVEN'),publishedAt:timestamp('published_at',{withTimezone:true}).notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}),firstPublishedAt:timestamp('first_published_at',{withTimezone:true}),heroImage:text('hero_image'),featured:boolean('featured').notNull().default(false),breaking:boolean('breaking').notNull().default(false),homepagePriority:smallint('homepage_priority').notNull().default(50),readingTime:smallint('reading_time'),trendingOverride:boolean('trending_override'),createdAt},table=>[index('articles_published_at_idx').on(table.publishedAt)]);
export const articleTranslations=pgTable('article_translations',{id:uuid('id').defaultRandom().primaryKey(),articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),locale:text('locale').notNull(),slug:text('slug').notNull(),title:text('title').notNull(),seoTitle:text('seo_title'),description:text('description'),heroAlt:text('hero_alt'),contentPath:text('content_path').notNull(),createdAt,updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},table=>[unique().on(table.articleId,table.locale),unique().on(table.locale,table.slug),index('article_translations_locale_slug_idx').on(table.locale,table.slug)]);
export const tags=pgTable('tags',{id:uuid('id').defaultRandom().primaryKey(),slug:text('slug').notNull().unique(),name:text('name').notNull()});
export const articleTags=pgTable('article_tags',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),tagId:uuid('tag_id').notNull().references(()=>tags.id,{onDelete:'cascade'})},table=>[primaryKey({columns:[table.articleId,table.tagId]})]);
export const articleSources=pgTable('article_sources',{id:uuid('id').defaultRandom().primaryKey(),articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),name:text('name').notNull(),url:text('url').notNull(),position:integer('position').notNull()},table=>[unique().on(table.articleId,table.url),unique().on(table.articleId,table.position)]);
export const articleStats=pgTable('article_stats',{articleId:uuid('article_id').primaryKey().references(()=>articles.id,{onDelete:'cascade'}),readCount:bigint('read_count',{mode:'number'}).notNull().default(0),engagedReadCount:bigint('engaged_read_count',{mode:'number'}).notNull().default(0),uniqueVisitorCount:bigint('unique_visitor_count',{mode:'number'}).notNull().default(0),totalEngagedSeconds:bigint('total_engaged_seconds',{mode:'number'}).notNull().default(0),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()});
export const articleStatsHourly=pgTable('article_stats_hourly',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),bucketStart:timestamp('bucket_start',{withTimezone:true}).notNull(),views:integer('views').notNull().default(0),uniqueVisitors:integer('unique_visitors').notNull().default(0),engagedReads:integer('engaged_reads').notNull().default(0),totalEngagedSeconds:integer('total_engaged_seconds').notNull().default(0)},table=>[primaryKey({columns:[table.articleId,table.bucketStart]}),index('article_stats_hourly_article_bucket_idx').on(table.articleId,table.bucketStart)]);
export const articleStatsDaily=pgTable('article_stats_daily',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),day:date('date').notNull(),views:integer('views').notNull().default(0),uniqueVisitors:integer('unique_visitors').notNull().default(0),engagedReads:integer('engaged_reads').notNull().default(0),totalEngagedSeconds:integer('total_engaged_seconds').notNull().default(0)},table=>[primaryKey({columns:[table.articleId,table.day]}),index('article_stats_daily_article_day_idx').on(table.articleId,table.day)]);
export const articleTrafficDaily=pgTable('article_traffic_daily',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),day:date('date').notNull(),source:text('source').notNull(),medium:text('medium').notNull(),views:integer('views').notNull().default(0),engagedReads:integer('engaged_reads').notNull().default(0)},table=>[primaryKey({columns:[table.articleId,table.day,table.source,table.medium]})]);
export const articleVisitorReads=pgTable('article_visitor_reads',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),visitorHash:text('visitor_hash').notNull(),lastReadAt:timestamp('last_read_at',{withTimezone:true}).notNull().defaultNow()},table=>[primaryKey({columns:[table.articleId,table.visitorHash]})]);
export const articleRelations=pgTable('article_relations',{articleId:uuid('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),relatedArticleId:uuid('related_article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),relationType:text('relation_type').notNull().default('related'),position:smallint('position').notNull().default(0),createdAt},table=>[primaryKey({columns:[table.articleId,table.relatedArticleId,table.relationType]})]);
export const articleLinkStats=pgTable('article_link_stats',{fromArticleId:uuid('from_article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),toArticleId:uuid('to_article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),clicks:bigint('clicks',{mode:'number'}).notNull().default(0),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},table=>[primaryKey({columns:[table.fromArticleId,table.toArticleId]})]);
