import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import {z} from 'zod';
import {categories, SlugSchema, StoryStateSchema} from './editorial-batch';
import type {Locale} from './i18n';

export {categories};
export type Category = (typeof categories)[number];
export const ArticleFrontmatterSchema = z.object({title:z.string().min(1),seoTitle:z.string().min(1).optional(),slug:SlugSchema,description:z.string().min(1),date:z.string().datetime({offset:true}),updatedAt:z.string().datetime({offset:true}).optional(),category:z.enum(categories),tags:z.array(z.string().min(1)).default([]),author:z.string().min(1).default('ELEVEN'),featured:z.boolean().default(false),breaking:z.boolean().default(false),trending:z.boolean().default(false),homepagePriority:z.number().int().min(0).max(100).default(0),heroImage:z.string().regex(/^\/images\/articles\/[a-z0-9-]+\.png$/).optional(),heroAlt:z.string().min(1).default('Imagen editorial de fútbol'),readingTime:z.number().int().positive().default(5),storyState:StoryStateSchema.default('NEW'),updateOf:SlugSchema.optional(),relatedPublishedSlug:SlugSchema.optional(),sources:z.array(z.object({name:z.string().min(1),url:z.string().url()})).default([])}).superRefine((article,context)=>{if(article.storyState==='UPDATE'&&!article.updateOf)context.addIssue({code:z.ZodIssueCode.custom,path:['updateOf'],message:'UPDATE requires updateOf.'});if(article.storyState==='EVERGREEN_REVISIT'&&!article.relatedPublishedSlug)context.addIssue({code:z.ZodIssueCode.custom,path:['relatedPublishedSlug'],message:'EVERGREEN_REVISIT requires relatedPublishedSlug.'});if(article.storyState==='NEW'&&(article.updateOf||article.relatedPublishedSlug))context.addIssue({code:z.ZodIssueCode.custom,message:'NEW articles cannot declare published-story relations.'});if(article.storyState==='UPDATE'&&article.relatedPublishedSlug)context.addIssue({code:z.ZodIssueCode.custom,path:['relatedPublishedSlug'],message:'UPDATE uses updateOf, not relatedPublishedSlug.'});if(article.storyState==='EVERGREEN_REVISIT'&&article.updateOf)context.addIssue({code:z.ZodIssueCode.custom,path:['updateOf'],message:'EVERGREEN_REVISIT uses relatedPublishedSlug, not updateOf.'});if(article.updateOf===article.slug||article.relatedPublishedSlug===article.slug)context.addIssue({code:z.ZodIssueCode.custom,message:'An article cannot relate to itself.'});});
export type Article=z.infer<typeof ArticleFrontmatterSchema>&{body:string}; export type ArticleRelation={slug:string;type:'update_of'|'related_published'}; const root=path.join(process.cwd(),'content/articles');
const directory=(locale:Locale)=>path.join(root,locale);
export function getAllArticles(locale:Locale='es'):Article[]{const dir=directory(locale);if(!fs.existsSync(dir))return [];const articles=fs.readdirSync(dir).filter(file=>file.endsWith('.md')).map(file=>{const parsed=matter(fs.readFileSync(path.join(dir,file),'utf8'));return {...ArticleFrontmatterSchema.parse(parsed.data),body:parsed.content}});return articles.sort((a,b)=>+new Date(b.date)-+new Date(a.date));}
export const getArticleBySlug=(slug:string,locale:Locale='es')=>getAllArticles(locale).find(article=>article.slug===slug);
export const getArticlesByCategory=(category:string,locale:Locale='es')=>getAllArticles(locale).filter(article=>article.category.toLowerCase()===category.toLowerCase());
export const getFeaturedArticle=(locale:Locale='es')=>getAllArticles(locale).filter(article=>article.featured).sort((a,b)=>b.homepagePriority-a.homepagePriority)[0]??getAllArticles(locale)[0];
export const getTrendingArticles=(locale:Locale='es')=>{const all=getAllArticles(locale);return [...all.filter(article=>article.trending),...all.filter(article=>!article.trending)]};
export const getBreakingArticles=(locale:Locale='es')=>getAllArticles(locale).filter(article=>article.breaking);
export function getArticleRelations(article:Pick<Article,'updateOf'|'relatedPublishedSlug'>):ArticleRelation[]{const relations:ArticleRelation[]=[];if(article.updateOf)relations.push({slug:article.updateOf,type:'update_of'});if(article.relatedPublishedSlug)relations.push({slug:article.relatedPublishedSlug,type:'related_published'});return relations;}
export function getRelatedArticles(article:Article,locale:Locale='es'){return getAllArticles(locale).filter(candidate=>candidate.slug!==article.slug).sort((a,b)=>{const score=(item:Article)=>Number(item.category===article.category)*3+item.tags.filter(tag=>article.tags.includes(tag)).length;return score(b)-score(a)||+new Date(b.date)-+new Date(a.date)}).slice(0,3)}
