import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {LanguageSelector} from '@/components/language-selector';
import {categorySlug,getDictionary,isLocale,locales,type Locale} from '@/lib/i18n';

export function generateStaticParams(){return locales.map((locale)=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const dictionary=getDictionary(locale);return {title:{default:`ELEVEN — ${dictionary.ui.tagline}`,template:'%s | ELEVEN'},description:dictionary.ui.tagline,alternates:{languages:{es:'/es',en:'/en',fr:'/fr'}}};}
export default async function LocaleLayout({children,params}:{children:React.ReactNode;params:Promise<{locale:string}>}){const {locale:rawLocale}=await params;if(!isLocale(rawLocale))notFound();const locale:Locale=rawLocale,dictionary=getDictionary(locale),ui=dictionary.ui;const navigation=['Actualidad','Historias','Táctica','Clubes','Jugadores','Datos'] as const;return <><header><div className="utility"><div className="shell"><span>{new Intl.DateTimeFormat(dictionary.localeTag,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date('2026-10-02T12:00:00+02:00'))}</span><span>{ui.tagline}</span><span>⌕</span></div></div><nav className="nav"><Link className="brand" href={`/${locale}`}>ELE<i>VEN</i></Link><div className="navlinks">{navigation.map((category)=><Link key={category} href={`/${locale}/category/${categorySlug(locale,category)}`}>{dictionary.categories[category]}</Link>)}</div><Link className="subscribe" href="#newsletter">{ui.subscribe}</Link><LanguageSelector locale={locale}/></nav></header><main className="shell">{children}</main><footer className="footer"><div className="shell"><b className="brand">ELE<i>VEN</i></b><span> · {dictionary.categories.Historias} · {dictionary.categories.Táctica} · {dictionary.categories.Cultura}</span><br/><br/>© 2026 ELEVEN.</div></footer></>}
